# Grab the latest alpine image
FROM microsoft/mssql-server-linux:latest

RUN -d --name sql_server_demo -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=reallyStrongPwd123' -p 1433:1433 microsoft/mssql-server-linux
